# Generated by Django 4.2.28 on 2026-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mufc_club_app', '0002_fanmessage_alter_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Coach name')),
                ('role', models.CharField(default='Head coach ', max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='coach/')),
                ('wiki_link', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='players/default_avatar.png', upload_to='players/'),
        ),
    ]
