# Generated by Django 4.2.28 on 2026-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mufc_club_app', '0004_clubinfo_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Picture at the gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
